# Generated by Django 6.0.1 on 2026-01-30 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CompanyInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Shivam Construction Company', max_length=200)),
                ('tagline', models.CharField(default='Civil Contractor & General Order Suppliers', max_length=300)),
                ('phone', models.CharField(default='6350092193', max_length=20)),
                ('email', models.EmailField(default='scccompany91@gmail.com', max_length=254)),
                ('address', models.TextField(default='BUILDING NO./FLAT NO.: MEEL COLONY KE SAMANE, ROAD/STREET: WARD NO. 03 NEW, CITY/TOWN/VILLAGE: SURATGARH, DISTRICT: SRI GANGANAGAR, STATE: RAJASTHAN, PIN CODE: 335804')),
                ('vision', models.TextField(blank=True)),
                ('quality_policy', models.TextField(blank=True)),
                ('introduction', models.TextField(blank=True)),
            ],
            options={
                'verbose_name_plural': 'Company Information',
            },
        ),
        migrations.CreateModel(
            name='CompletedProject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('work_awarded_by', models.CharField(max_length=200)),
                ('wo_reference', models.CharField(max_length=200)),
                ('type_of_work', models.CharField(max_length=300)),
                ('date', models.DateField()),
                ('order', models.IntegerField(default=0)),
            ],
            options={
                'verbose_name_plural': 'Completed Projects',
                'ordering': ['-date', 'order'],
            },
        ),
        migrations.CreateModel(
            name='Equipment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('quantity', models.IntegerField(default=0)),
                ('category', models.CharField(blank=True, max_length=100)),
                ('order', models.IntegerField(default=0)),
            ],
            options={
                'verbose_name_plural': 'Equipment',
                'ordering': ['category', 'order'],
            },
        ),
        migrations.CreateModel(
            name='KeyPerson',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('role', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('order', models.IntegerField(default=0)),
            ],
            options={
                'verbose_name_plural': 'Key Persons',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('industrial', 'Industrial and Commercial Buildings'), ('civil', 'Civil'), ('piping', 'Cross Country Piping')], max_length=50)),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('order', models.IntegerField(default=0)),
            ],
            options={
                'verbose_name_plural': 'Services',
                'ordering': ['category', 'order'],
            },
        ),
        migrations.CreateModel(
            name='Staff',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=200)),
                ('designation', models.CharField(max_length=200)),
                ('staff_type', models.CharField(choices=[('site', 'Site Staff'), ('central', 'Central Planner')], max_length=20)),
                ('team', models.CharField(blank=True, max_length=50)),
                ('quantity', models.IntegerField(default=1)),
                ('order', models.IntegerField(default=0)),
            ],
            options={
                'verbose_name_plural': 'Staff',
                'ordering': ['staff_type', 'order'],
            },
        ),
    ]
