# Generated by Django 6.0.1 on 2026-01-30 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shivam', '0002_companyimage_companyinfo_hero_image_companyinfo_logo_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='companyinfo',
            name='instagram_url',
            field=models.URLField(blank=True, default='https://www.instagram.com/shivamconstruction'),
        ),
    ]
