# Generated by Django 6.0.1 on 2026-01-30 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shivam', '0003_companyinfo_instagram_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='companyinfo',
            name='contact_bg',
            field=models.ImageField(blank=True, null=True, upload_to='company/backgrounds/', verbose_name='Contact Page Background'),
        ),
        migrations.AddField(
            model_name='companyinfo',
            name='equipment_bg',
            field=models.ImageField(blank=True, null=True, upload_to='company/backgrounds/', verbose_name='Equipment Page Background'),
        ),
        migrations.AddField(
            model_name='companyinfo',
            name='projects_bg',
            field=models.ImageField(blank=True, null=True, upload_to='company/backgrounds/', verbose_name='Projects Page Background'),
        ),
        migrations.AddField(
            model_name='companyinfo',
            name='quality_bg',
            field=models.ImageField(blank=True, null=True, upload_to='company/backgrounds/', verbose_name='Quality Section Background'),
        ),
        migrations.AddField(
            model_name='companyinfo',
            name='services_bg',
            field=models.ImageField(blank=True, null=True, upload_to='company/backgrounds/', verbose_name='Services Page Background'),
        ),
        migrations.AddField(
            model_name='companyinfo',
            name='team_bg',
            field=models.ImageField(blank=True, null=True, upload_to='company/backgrounds/', verbose_name='Team Page Background'),
        ),
        migrations.AddField(
            model_name='companyinfo',
            name='vision_bg',
            field=models.ImageField(blank=True, null=True, upload_to='company/backgrounds/', verbose_name='Vision Section Background'),
        ),
    ]
