# Generated by Django 6.0.1 on 2026-01-30 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shivam', '0004_companyinfo_contact_bg_companyinfo_equipment_bg_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('document_type', models.CharField(choices=[('work', 'Complete Work Documents'), ('experience', 'Experience Documents'), ('payment', 'Payment Documents'), ('certificate', 'Certificates'), ('other', 'Other Documents')], max_length=20)),
                ('file', models.FileField(upload_to='documents/%Y/%m/')),
                ('description', models.TextField(blank=True)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('order', models.IntegerField(default=0)),
            ],
            options={
                'verbose_name_plural': 'Documents',
                'ordering': ['document_type', 'order', '-uploaded_at'],
            },
        ),
    ]
