# Generated by Django 6.0.1 on 2026-01-30 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shivam', '0006_equipment_description_equipment_specifications_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='completedproject',
            options={'ordering': ['-date', 'order'], 'verbose_name_plural': 'Projects'},
        ),
        migrations.AddField(
            model_name='completedproject',
            name='status',
            field=models.CharField(choices=[('completed', 'Project Completed'), ('on_hand', 'Project On Hand'), ('ongoing', 'Ongoing Projects')], default='completed', max_length=20),
        ),
    ]
