# Generated by Django 6.0.1 on 2026-04-06 09:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shivam', '0007_alter_completedproject_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(blank=True, max_length=20)),
                ('message', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': 'Contact Messages',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='HomeBanner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('subtitle', models.CharField(blank=True, max_length=300)),
                ('tagline', models.CharField(blank=True, max_length=300)),
                ('media_type', models.CharField(choices=[('image', 'Image'), ('video', 'Video')], default='image', max_length=10)),
                ('image', models.ImageField(blank=True, null=True, upload_to='banners/images/')),
                ('video', models.FileField(blank=True, null=True, upload_to='banners/videos/')),
                ('button_text', models.CharField(blank=True, default='Learn More', max_length=80)),
                ('button_url', models.CharField(blank=True, default='/projects/', max_length=300)),
                ('secondary_button_text', models.CharField(blank=True, default='Contact Us', max_length=80)),
                ('secondary_button_url', models.CharField(blank=True, default='/contact/', max_length=300)),
                ('is_active', models.BooleanField(default=True)),
                ('order', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': 'Home Banners',
                'ordering': ['order', '-created_at'],
            },
        ),
    ]
