# Generated by Django 6.0.1 on 2026-06-12 05:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shivam', '0008_contactmessage_homebanner'),
    ]

    operations = [
        migrations.AddField(
            model_name='companyimage',
            name='description_hi',
            field=models.TextField(blank=True, verbose_name='Description (Hindi)'),
        ),
        migrations.AddField(
            model_name='companyimage',
            name='title_hi',
            field=models.CharField(blank=True, max_length=200, verbose_name='Title (Hindi)'),
        ),
        migrations.AddField(
            model_name='companyinfo',
            name='address_hi',
            field=models.TextField(blank=True, verbose_name='Address (Hindi)'),
        ),
        migrations.AddField(
            model_name='companyinfo',
            name='introduction_hi',
            field=models.TextField(blank=True, verbose_name='Introduction (Hindi)'),
        ),
        migrations.AddField(
            model_name='companyinfo',
            name='quality_policy_hi',
            field=models.TextField(blank=True, verbose_name='Quality Policy (Hindi)'),
        ),
        migrations.AddField(
            model_name='companyinfo',
            name='tagline_hi',
            field=models.CharField(blank=True, max_length=300, verbose_name='Tagline (Hindi)'),
        ),
        migrations.AddField(
            model_name='companyinfo',
            name='vision_hi',
            field=models.TextField(blank=True, verbose_name='Vision (Hindi)'),
        ),
        migrations.AddField(
            model_name='completedproject',
            name='type_of_work_hi',
            field=models.CharField(blank=True, max_length=300, verbose_name='Type of Work (Hindi)'),
        ),
        migrations.AddField(
            model_name='completedproject',
            name='work_awarded_by_hi',
            field=models.CharField(blank=True, max_length=200, verbose_name='Work Awarded By (Hindi)'),
        ),
        migrations.AddField(
            model_name='document',
            name='description_hi',
            field=models.TextField(blank=True, verbose_name='Description (Hindi)'),
        ),
        migrations.AddField(
            model_name='document',
            name='title_hi',
            field=models.CharField(blank=True, max_length=200, verbose_name='Title (Hindi)'),
        ),
        migrations.AddField(
            model_name='equipment',
            name='category_hi',
            field=models.CharField(blank=True, max_length=100, verbose_name='Category (Hindi)'),
        ),
        migrations.AddField(
            model_name='equipment',
            name='description_hi',
            field=models.TextField(blank=True, verbose_name='Description (Hindi)'),
        ),
        migrations.AddField(
            model_name='equipment',
            name='name_hi',
            field=models.CharField(blank=True, max_length=200, verbose_name='Name (Hindi)'),
        ),
        migrations.AddField(
            model_name='equipment',
            name='specifications_hi',
            field=models.TextField(blank=True, verbose_name='Specifications (Hindi)'),
        ),
        migrations.AddField(
            model_name='equipmentimage',
            name='description_hi',
            field=models.TextField(blank=True, verbose_name='Description (Hindi)'),
        ),
        migrations.AddField(
            model_name='equipmentimage',
            name='title_hi',
            field=models.CharField(blank=True, max_length=200, verbose_name='Title (Hindi)'),
        ),
        migrations.AddField(
            model_name='homebanner',
            name='button_text_hi',
            field=models.CharField(blank=True, max_length=80, verbose_name='Button Text (Hindi)'),
        ),
        migrations.AddField(
            model_name='homebanner',
            name='secondary_button_text_hi',
            field=models.CharField(blank=True, max_length=80, verbose_name='Secondary Button (Hindi)'),
        ),
        migrations.AddField(
            model_name='homebanner',
            name='subtitle_hi',
            field=models.CharField(blank=True, max_length=300, verbose_name='Subtitle (Hindi)'),
        ),
        migrations.AddField(
            model_name='homebanner',
            name='tagline_hi',
            field=models.CharField(blank=True, max_length=300, verbose_name='Tagline (Hindi)'),
        ),
        migrations.AddField(
            model_name='homebanner',
            name='title_hi',
            field=models.CharField(blank=True, max_length=200, verbose_name='Title (Hindi)'),
        ),
        migrations.AddField(
            model_name='keyperson',
            name='description_hi',
            field=models.TextField(blank=True, verbose_name='Description (Hindi)'),
        ),
        migrations.AddField(
            model_name='keyperson',
            name='role_hi',
            field=models.CharField(blank=True, max_length=200, verbose_name='Role (Hindi)'),
        ),
        migrations.AddField(
            model_name='service',
            name='description_hi',
            field=models.TextField(blank=True, verbose_name='Description (Hindi)'),
        ),
        migrations.AddField(
            model_name='service',
            name='title_hi',
            field=models.CharField(blank=True, max_length=200, verbose_name='Title (Hindi)'),
        ),
        migrations.AddField(
            model_name='staff',
            name='designation_hi',
            field=models.CharField(blank=True, max_length=200, verbose_name='Designation (Hindi)'),
        ),
        migrations.AlterField(
            model_name='homebanner',
            name='media_type',
            field=models.CharField(choices=[('video', 'Video')], default='video', max_length=10),
        ),
    ]
