# Generated by Django 6.0.1 on 2026-09-25 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shivam', '0009_bilingual_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='keyperson',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='team/', verbose_name='Photo / CEO image'),
        ),
        migrations.AlterField(
            model_name='companyinfo',
            name='tagline',
            field=models.CharField(default='Road Earthwork, Soil Leveling & Canal Lining Contractor', max_length=300),
        ),
        migrations.AlterField(
            model_name='service',
            name='category',
            field=models.CharField(choices=[('road', 'Road Earthwork & Soil Leveling'), ('bridge', 'Bridge & Flyover Earthwork'), ('canal', 'Canal & Nahar Lining (Rajasthan)')], max_length=50),
        ),
    ]
